# This is a basic workflow to help you get started with Actions

name: Run Python Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if [ "$RUNNER_OS" == "Linux" ]; then
              sudo apt install firefox-geckodriver
          elif [ "$RUNNER_OS" == "macOS" ]; then
              brew install geckodriver
          else
              echo "$RUNNER_OS not supported"
              exit 1
          fi
        
      - name: Run tests with unittest and gather coverage data
        run:  cd api && coverage run -m unittest discover
          
      - name: Test selenium
        run: |
          cd e2e && coverage run -m unittest
          coverage xml
          
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests # optional
          verbose: true # optional (default = false)
          fail_ci_if_error: true
